apiVersion: v1
kind: Namespace
metadata:
  name: test-ec2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-producer
  namespace: test-ec2
  labels:
    app: test-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-producer
  template:
    metadata:
      labels:
        app: test-producer
    spec:
      serviceAccountName: default
      nodeSelector:
        NodeType: worker
      containers:
      - name: producer
        image: 521176574385.dkr.ecr.sa-east-1.amazonaws.com/dry-run-brq-producer:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "sa-east-1"
        - name: PROJECT_NAME
          value: "dry-run-brq"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "b-1.dryrunbrqmsk.cxgo3g.c2.kafka.sa-east-1.amazonaws.com:9098,b-2.dryrunbrqmsk.cxgo3g.c2.kafka.sa-east-1.amazonaws.com:9098"
        - name: S3_INPUT_BUCKET
          value: "dry-run-brq-input-521176574385"
        - name: S3_REJECTED_BUCKET
          value: "dry-run-brq-rejected-521176574385"
        - name: DYNAMODB_PROCESSED_FILES_TABLE
          value: "dry-run-brq-processed-files"
        - name: KAFKA_TRANSACTIONS_TOPIC
          value: "transactions"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
